config/routes.rb
Rails.application.routes.draw do
  # Defines the root path route ("/")
  root "pages#home"

  # Authenticate through devise and omniauth
  devise_for :users,
             controllers: { omniauth_callbacks: "users/omniauth_callbacks" },
             skip: [ :sessions ]

  # Disable the `POST "/users/sign_in"` route.
  # Prevents username/password logins. We only support omniauth.
  devise_scope :user do
    get "/users/sign_in", to: "devise/sessions#new", as: :new_user_session
    delete "/users/sign_out", to: "devise/sessions#destroy", as: :destroy_user_session
  end

  resources :tasks do
    resources :applications,
              controller: "tasks/applications",
              only: [ :create, :destroy, :update ],
              param: :user_id
    patch "/applications/:user_id/status",
          to: "tasks/applications/statuses#update",
          as: :application_status
    put "/applications/:user_id/status",
        to: "tasks/applications/statuses#update",
        as: nil
  end
  get "/tasks/new/from-preset/:project_id/:coordinator_ids", to: "tasks/from_preset#new", as: :new_task_from_preset

  resources :projects do
    resources :tasks, only: %i[ index ]
  end

  namespace :coordinators do
    resources :searches, only: %i[ index create ]
  end

  resources :dashboard, only: %i[ index ]

  resources :admin, only: %i[ index ]
  namespace :admin do
    resources :legal, only: %i[ index ]
    resource :footer, only: %i[ edit ], controller: :footer
    namespace :footer do
      resource :copyright, only: %i[ update ], controller: :copyright
      resource :sitemap, only: %i[ update destroy ], controller: :sitemap
    end
    resource :brand, only: %i[ edit ], controller: :brand
    namespace :brand do
      resource :name, only: %i[ update ], controller: :name
      resource :logo, only: %i[ update destroy ], controller: :logo
    end
    namespace :users do
      resources :roles, only: %i[ index update ]
    end
  end

  get "/profile", to: "users/profile#edit"
  delete "/profile", to: "users/profile#destroy"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :legal, param: :slug, only: %i[ show edit update destroy ], controller: "pages/legal"

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  authenticate :user, ->(user) { user.admin? } do
    mount MissionControl::Jobs::Engine, at: "/admin/monitoring/jobs"
    mount ActiveStorageDashboard::Engine, at: "/admin/monitoring/storage"
  end
end

app/controllers/admin/legal_controller.rb
# frozen_string_literal: true

module Admin
  class LegalController < ApplicationController
    LEGAL_PAGES = %w[ imprint privacy-policy terms-of-service ]

    def index
      authorize! :show, :admin_settings

      @pages = Page.where(slug: LEGAL_PAGES).pluck(:slug)
    end
  end
end

app/controllers/pages/legal_controller.rb
module Pages
  class LegalController < ApplicationController
    LEGAL_PAGES = %w[ imprint privacy-policy terms-of-service ]

    before_action :set_page, only: %i[ show destroy ]
    before_action :set_editable_page, only: %i[ edit update ]

    def show; end

    def edit
      authorize! :edit, @page
    end

    def update
      authorize! :update, @page

      if @page.update(page_params)
        flash[:notice] = "Page was successfully updated."
        redirect_to legal_path(@page.slug)
      else
        render :edit, status: :unprocessable_content
      end
    end

    def destroy
      authorize! :destroy, @page

      @page.destroy if @page.present?
      flash[:notice] = "Page was successfully deleted."
      redirect_to root_path
    end

    private

    def set_page
      raise ActionController::RoutingError, "Not Found" unless is_legal_page

      @page = Page.find_by(slug: params[:slug])
    end

    def set_editable_page
      raise ActionController::RoutingError, "Not Found" unless is_legal_page

      @page = Page.find_or_initialize_by(slug: params[:slug])
    end

    def page_params
      params.require(:page).permit(:content)
    end

    def is_legal_page
      params[:slug].in?(LEGAL_PAGES)
    end
  end
end

app/views/admin/legal/index.html.erb
<%= render TendrilTasks::Content.new(width: :large) do %>
  <%= render TendrilTasks::Breadcrumb.new do |breadcrumb| %>
    <% breadcrumb.home %>
    <% breadcrumb.item t("breadcrumbs.admin"), href: admin_index_path %>
    <% breadcrumb.item t("admin.legal.title") %>
  <% end %>

  <%= render TendrilTasks::Heading.new(tag: :h1) do %>
    <%= t("admin.legal.title") %>
  <% end %>

  <div>
    <p class="mb-6 text-lg font-normal text-gray-500 lg:text-xl dark:text-gray-400"><%= t(".description") %></p>
  </div>

  <ul class="my-4 space-y-3">
    <% Admin::LegalController::LEGAL_PAGES.each do |slug| %>
      <% if slug.in?(@pages) %>
        <li>
          <span class="flex items-center p-3 text-base font-bold text-gray-900 rounded-lg bg-gray-50 hover:bg-gray-100 group hover:shadow dark:bg-gray-600 dark:hover:bg-gray-500 dark:text-white">
            <span class="flex-1 ms-3 font-medium dark:text-white whitespace-nowrap truncate">
              <%= link_to legal_path(slug), class: "hover:underline" do %>
                <%= t("pages.#{slug}.title") %>
              <% end %>
            </span>
            <%= render Gustwave::Button.new(t(".edit"),
                                            tag: :a,
                                            href: edit_legal_path(slug)) do |button| %>
              <% button.leading_icon :edit %>
            <% end %>
          </span>
        </li>
      <% else %>
        <li>
          <span class="flex items-center p-3 text-base font-bold text-gray-900 rounded-lg bg-gray-50 hover:bg-gray-100 group hover:shadow dark:bg-gray-600 dark:hover:bg-gray-500 dark:text-white">
            <span class="flex-1 ms-3 font-medium dark:text-white whitespace-nowrap truncate">
              <%= t("pages.#{slug}.title") %>
            </span>
            <%= render Gustwave::Button.new(t(".create"),
                                            tag: :a,
                                            href: edit_legal_path(slug)) do |button| %>
              <% button.leading_icon :plus %>
            <% end %>
          </span>
        </li>
      <% end %>
    <% end %>
  </ul>
<% end %>