config/routes.rb
Rails.application.routes.draw do
  # Defines the root path route ("/")
  root "pages#home"

  # Authenticate through devise and omniauth
  devise_for :users,
             controllers: { omniauth_callbacks: "users/omniauth_callbacks" },
             skip: [ :sessions ]

  # Disable the `POST "/users/sign_in"` route.
  # Prevents username/password logins. We only support omniauth.
  devise_scope :user do
    get "/users/sign_in", to: "devise/sessions#new", as: :new_user_session
    delete "/users/sign_out", to: "devise/sessions#destroy", as: :destroy_user_session
  end

  resources :tasks do
    resources :applications,
              controller: "tasks/applications",
              only: [ :create, :destroy, :update ],
              param: :user_id
    patch "/applications/:user_id/status",
          to: "tasks/applications/statuses#update",
          as: :application_status
    put "/applications/:user_id/status",
        to: "tasks/applications/statuses#update",
        as: nil
  end
  get "/tasks/new/from-preset/:project_id/:coordinator_ids", to: "tasks/from_preset#new", as: :new_task_from_preset

  resources :projects do
    resources :tasks, only: %i[ index ]
  end

  namespace :coordinators do
    resources :searches, only: %i[ index create ]
  end

  resources :dashboard, only: %i[ index ]

  resources :admin, only: %i[ index ]
  namespace :admin do
    resources :legal, only: %i[ index ]
    resource :footer, only: %i[ edit ], controller: :footer
    namespace :footer do
      resource :copyright, only: %i[ update ], controller: :copyright
      resource :sitemap, only: %i[ update destroy ], controller: :sitemap
    end
    resource :brand, only: %i[ edit ], controller: :brand
    namespace :brand do
      resource :name, only: %i[ update ], controller: :name
      resource :logo, only: %i[ update destroy ], controller: :logo
    end
    namespace :users do
      resources :roles, only: %i[ index update ]
    end
  end

  get "/profile", to: "users/profile#edit"
  delete "/profile", to: "users/profile#destroy"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :legal, param: :slug, only: %i[ show edit update destroy ], controller: "pages/legal"

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  authenticate :user, ->(user) { user.admin? } do
    mount MissionControl::Jobs::Engine, at: "/admin/monitoring/jobs"
    mount ActiveStorageDashboard::Engine, at: "/admin/monitoring/storage"
  end
end

app/models/task.rb
class Task < ApplicationRecord
  include RichTextSanitizer

  NEW_TASK_THRESHOLD = 2.weeks

  belongs_to :project
  has_and_belongs_to_many :coordinators,
                          class_name: "User",
                          join_table: "task_coordinators",
                          association_foreign_key: "user_id",
                          foreign_key: "task_id"

  has_many :task_applications, dependent: :destroy
  has_many :applicants, through: :task_applications, source: :user

  has_rich_text :description
  has_sanitized_plain_text :description_plain_text, :description

  validates :title, presence: true
  validates :description, presence: true
  validates :coordinators, presence: true

  scope :publicly_visible, -> {
    is_published.includes(:project)
                .where(project: { published_at: ...Time.zone.now })
  }

  scope :is_published, -> {
    where(published_at: ...Time.zone.now)
  }

  # Tasks without coordinators
  #
  # This happens when a user is deleted and the task is not reassigned to
  # another user.
  scope :orphaned, -> {
    left_outer_joins(:coordinators).where(task_coordinators: { user_id: nil }).distinct
  }

  # Returns true if the task is considered as new
  def new?
    created_at > NEW_TASK_THRESHOLD.ago
  end

  # Returns true if the task has no coordinators
  def orphaned?
    coordinators.empty?
  end

  def applicant?(user)
    applicants.include?(user) &&
      !task_applications.find_by(user_id: user.id).withdrawn?
  end

  def visible?
    published? && self.project.published?
  end

  def published?
    published_at.present? && published_at <= Time.zone.now
  end

  def publish
    self.published_at = Time.zone.now unless published?
  end

  def unpublish
    self.published_at = nil
  end
end

app/controllers/tasks/applications/statuses_controller.rb
# frozen_string_literal: true

module Tasks
  module Applications
    class StatusesController < ApplicationController
      before_action :set_task_application, only: [ :update ]

      def update
        authorize! :coordinate, @task_application.task
        unless @task_application.withdrawn?
          @task_application.update!(status_params)
        end
      end

      private

      def status_params
        params.permit(:status)
      end

      def set_task_application
        @task_application = TaskApplication
                              .includes(:task)
                              .find_by(
                                task_id: params[:task_id],
                                user_id: params[:user_id])
      end
    end
  end
end

app/controllers/tasks/applications_controller.rb
class Tasks::ApplicationsController < ApplicationController
  before_action :set_task, only: [ :create, :destroy, :update ]

  def create
    authorize! :read, @task

    TaskApplication.transaction do
      # Clear out any old application
      @application = TaskApplication.destroy_by(
        task_id: params[:task_id],
        user_id: current_user.id
      )

      # Create new entry
      @application = TaskApplication.new(
        task_id: params[:task_id],
        user_id: current_user.id,
        comment: params[:task_application][:comment].presence
      )
      @application.save!
    end
  end

  def update
    authorize! :read, @task

    @updated = false
    @application = TaskApplication.find_by(
      task_id: params[:task_id],
      user_id: current_user.id
    )
    if @application.editable?
      @application.comment = params[:task_application][:comment].presence
      @application.save!
      @updated = true
    end
  end

  def destroy
    authorize! :read, @task

    @application = TaskApplication.find_by(
      task_id: @task.id,
      user_id: current_user.id
    )

    # Within the grace period, just delete the application. Coordinators haven't
    # been notified yet.
    if @application.editable?
      @application.destroy!
    # After the grace period, set the application to withdrawn. The application
    # will be still shown to the coordinators with the withdrawn status, until
    # the user reapplies.
    else
      @application.withdraw
      @application.save!
    end
  end

  private

  def set_task
    @task = Task.find(params[:task_id])
  end
end

app/controllers/tasks/from_preset_controller.rb
# frozen_string_literal: true

module Tasks
  class FromPresetController < ApplicationController
    rescue_from CanCan::AccessDenied, with: :access_denied_handler

    def new
      authorize! :create, Task

      @task_form = TaskForm.new(preset_params)

      lookup_context.prefixes.prepend("tasks")
      render "tasks/new"
    end

    private

    def preset_params
      return nil unless params[:project_id].present?

      preset = {}
      preset[:project_id] = params[:project_id]
      preset[:coordinator_ids] = params[:coordinator_ids].split("-")
      preset
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [ :show, :edit, :update, :destroy ]
  authorize_resource
  before_action :set_task_form, only: [ :edit, :update ]

  rescue_from CanCan::AccessDenied, with: :access_denied_handler

  def index
    filter = params.permit(:project_id)
    @type = :all_published_tasks

    @projects = Project.select(:id, :title)
                       .publicly_visible
                       .order_by_most_recently_published_task

    @tasks = Task.publicly_visible
                 .includes(:coordinators, :project, :applicants)

    # Apply filters
    if filter[:project_id].present?
      @type = :tasks_for_project
      # Raises an ActiveRecord::RecordNotFound exception when trying to access
      # a non-existing or non-authorized project
      @selected_project = @projects.find(filter[:project_id])
      # Apply project filter
      @tasks = @tasks.where(project_id: filter[:project_id])
    end

    @tasks = @tasks.order(created_at: :desc)
  end

  def show
    if can?(:coordinate, @task)
      @task_applications = TaskApplication
                             .where(task: @task)
                             .includes(:user, :task)
                             .order(created_at: :desc)
    end
  end

  def new
    @task_form = TaskForm.new
    @task_form.coordinators << current_user
  end

  def create
    @task_form = TaskForm.new(task_form_params)

    if @task_form.save
      success_msg = toast_message_for(@task_form.task, :create)
      if @task_form.submit_type == "save_and_new"
        redirect_to new_task_from_preset_path(project_id: @task_form.project.id, coordinator_ids: @task_form.project.coordinators.join("-")), notice: success_msg
      else
        redirect_to task_path(@task_form.task), notice: success_msg
      end
    else
      render :new, status: :unprocessable_content
    end
  end

  def edit; end

  def update
    @task_form.assign_attributes(task_form_params)
    task_has_changed = @task_form.changed?

    if @task_form.save
      update_msg = toast_message_for(@task_form.task, :update) if task_has_changed
      redirect_to task_path(@task_form.task), notice: update_msg
    else
      render :edit, status: :unprocessable_content
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_path, notice: toast_message_for(@task, :destroy)
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def set_task_form
    @task_form = TaskForm.new(@task)
  end

  def task_form_params
    params[:task_form][:coordinator_ids] = params[:assigned_coordinator_ids]
    params.require(:task_form)
          .permit(:project_id, :title, :description, :publish, :submit_type, coordinator_ids: [])
  end
end

app/helpers/tasks_helper.rb
# frozen_string_literal: true

module TasksHelper
  def task_form_url(task_form)
    task_form.task.persisted? ? task_path(task_form.task) : tasks_path
  end

  def task_form_method(task_form)
    task_form.task.persisted? ? :patch : :post
  end
end

app/views/tasks/_coordinators_search_modal.html.erb
<%# turbo_frame_tag "coordinator-search-modal", tabindex: -1, aria_hidden: true, data: { modal_backdrop: "static" }, class: "hidden overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 justify-center items-center w-full md:inset-0 h-[calc(100%-1rem)] max-h-full" do %>
<div id="coordinator-search-modal" tabindex="-1" aria-hidden="true" data-modal-backdrop="static" class="hidden overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 justify-center items-center w-full md:inset-0 h-[calc(100%-1rem)] max-h-full">
  <div class="relative p-4 w-full max-w-2xl max-h-full">
    <!-- Modal content -->
    <div class="relative bg-white rounded-lg shadow dark:bg-gray-700">
      <!-- Modal header -->
      <div class="flex items-center justify-between p-4 md:p-5 border-b rounded-t dark:border-gray-600">
        <h3 class="text-lg font-semibold text-gray-900 dark:text-white">
          Ansprechpersonen bearbeiten
        </h3>
        <button type="button" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm h-8 w-8 ms-auto inline-flex justify-center items-center dark:hover:bg-gray-600 dark:hover:text-white" data-modal-hide="coordinator-search-modal">
          <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
          </svg>
          <span class="sr-only">Close modal</span>
        </button>
      </div>
      <!-- Modal body -->

      <%= form_with url: coordinators_searches_path,
                    method: :post,
                    data: {
                        controller: "auto-focus auto-submit list-mover dim-backdrop",
                        turbo_stream: "true"
                    },
                    class: "mx-auto" do |f| %>
        <div class="p-4 md:p-5">
          <%# Search box %>
          <div class="min-h-96 space-y-4">
            <label for="search" class="text-sm font-normal text-gray-500 dark:text-gray-400">Wähle zusätzliche Ansprechpersonen aus</label>
            <%# Search field %>
            <%= f.text_field :search,
                             placeholder: "Suche nach Namen oder Benutzernamen",
                             data: {
                                 action: "input->auto-submit#delayed",
                                 auto_focus_target: "focusHere"
                             },
                             autocomplete: "off",
                             class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" do %>
            <% end %>
            <%# Search field submit button %>
            <%# Auto submit the search field through a GET request %>
            <%= f.submit "Suchen", data: { auto_submit_target: "submit" }, class: "sr-only", tabindex: "-1", formmethod: "get" %>
            <%# Search results %>
            <ul id="candidates" class="flex flex-wrap gap-2 min-rows">
              <%= render partial: "coordinator_item",
                         collection: @task_form.coordinator_options,
                         as: :coordinator,
                         locals: { target: "modal", is_checked: false } %>
            </ul>
          </div>

          <%# Chosen coordinators %>
          <div class="min-h-36 space-y-4">
            <p class="text-sm font-normal text-gray-500 dark:text-gray-400">Ausgewählte Ansprechpersonen</p>
            <ul id="coordinators"
                class="flex flex-wrap gap-2 my-4">
              <%= render partial: "coordinator_item",
                         collection: @task_form.coordinators,
                         as: :coordinator,
                         locals: { target: "modal", is_checked: true } %>
            </ul>
          </div>
        </div>
        <div class="flex items-center justify-between p-4 md:p-5 border-t rounded-b dark:border-gray-600">
          <%= render ButtonComponent.new({ class: "w-full", data: { "modal-hide": "coordinator-search-modal" } }).with_content("Auswahl übernehmen") %>
        </div>
      <% end # of form %>
    </div>
  </div>
</div>
<%# end %>

app/views/tasks/_form.html.erb
<% form_object = TaskForm.new if false %>
<%= form_with model: form_object,
              url: form_object.form_path,
              method: form_object.form_method,
              class: "mx-auto space-y-4" do |f|
%>
  <%= render Form::SelectComponent.new(
      f,
      :project_id,
      Project.model_name.human,
      form_object.project_options, :id, :title,
      error_field_attribute: :project,
      prompt: t(".choose_initiative"),
      selected: form_object.project&.id) do |project_select|
  %>
    <% project_select.trailing_button(tag: :a, href: new_project_path).with_content(t(".new_initiative_button")) %>
  <% end %>
  <%= render Form::TextFieldComponent.new(f, :title) %>
  <%= render Form::RichTextAreaComponent.new(f, :description) do |with| %>
    <% with.disabled_buttons(:heading1, :heading2, :heading3) %>
  <% end %>
  <%= render Form::CoordinatorPickerComponent.new(f, :coordinators) %>
  <%= render Form::ToggleComponent.new(f, :publish, t(".visibility")) do |toggle| %>
    <% toggle.checked_state_text(t(".private")) %>
    <% toggle.unchecked_state_text(t(".public")) %>
  <% end %>

  <% if form_object.persisted? %>
    <%= render Form::SubmitButtonGroupComponent.new(f) do |button_group| %>
      <% button_group.delete_button(t("forms.delete"), target_modal_id: "confirm-task-delete") %>
      <% button_group.button(t("forms.update")) %>
    <% end %>
  <% else %>
    <%= render Form::SubmitButtonGroupComponent.new(f) do |button_group| %>
      <% button_group.button(t("forms.create"), value: "save") %>
      <% button_group.button(t(".save_and_new"), value: "save_and_new") %>
    <% end %>
  <% end %>
<% end %>

<%= content_for :modal do %>
  <%= render DeleteConfirm::ModalComponent.new(
      id: "confirm-task-delete",
      delete_path: form_object.form_path) do |modal| %>
    <% modal.heading(t(".delete_confirm.modal.title")) %>
    <% paragraphize(t(".delete_confirm.modal.content")).each do |text| %>
      <%= modal.paragraph(text) %>
    <% end %>
  <% end %>
<% end %>

app/views/tasks/_form_label.html.erb
<%= form.label target, text, class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>

app/views/tasks/edit.html.erb
<%= render TendrilTasks::Content.new(width: :large) do %>
  <%= render TendrilTasks::Breadcrumb.new do |breadcrumb| %>
    <% breadcrumb.home %>
    <% breadcrumb.item(Task.model_name.human(count: 2), href: tasks_path) %>
    <% breadcrumb.item(@task_form.title, href: task_path(@task_form.task)) %>
    <% breadcrumb.item(t("breadcrumbs.edit")) %>
  <% end %>

  <%= render TendrilTasks::Heading
               .new(tag: :h1)
               .with_content(t(".edit_task"))
  %>

  <%= render 'form', form_object: @task_form %>
<% end %>

app/views/tasks/index.html.erb
<%= render TendrilTasks::Content.new do %>
  <%# Headline %>
  <% case @type %>
  <% when :all_published_tasks %>
    <%= render 'tasks/index/headline_for_all_published_tasks',
               count: @tasks.size
    %>
  <% else %>
    <%= render partial: 'tasks/index/headline_for_filtered_by_initiative',
               locals: {
                 count: @tasks.size,
                 project: @selected_project
               }
    %>
  <% end %>

  <%# Filter by projects %>
  <% if @projects.size > 0 %>
    <% is_selected = current_page?(tasks_path) %>
    <ul id="filter-by-project" class="flex flex-wrap gap-2">
      <li>
        <%= render Gustwave::Badge.new(
          t(".filter_by_project.show_all"),
          tag: (is_selected ? :span : :a),
          href: (tasks_path unless is_selected),
          size: :sm,
          outline: is_selected,
          class: "md:text-lg md:font-semibold")
        %>
      </li>
      <% @projects.each do |project| %>
        <% is_selected = current_page?(project_tasks_path(project)) %>
        <li>
          <%= render Gustwave::Badge.new(
            project.title,
            tag: is_selected ? :span : :a,
            href: (project_tasks_path(project) unless is_selected),
            size: :sm,
            scheme: badge_scheme_by_id(project.id),
            outline: is_selected,
            class: "md:text-lg md:font-semibold")
          %>
        </li>
      <% end %>
    </ul>
  <% end %>

  <%# Tasks displayed as cards in a grid %>
  <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
    <% @tasks.each do |task| %>
      <%= render TendrilTasks::Tasks::Card.new(task) %>
    <% end %>
  </div>
  <%= render TendrilTasks::HorizontalLine.new %>

  <%= render TendrilTasks::ButtonGrid.new(orientation: :vertical, size: :lg) do |grid| %>
    <%# Link to all tasks when filter is applied %>
    <% grid
         .button(tag: :a,
                 href: tasks_path,
                 scheme: :alternative,
                 class: "w-full text-center")
         .with_content(t ".view_all_tasks") if @type != :all_published_tasks
    %>

    <%# Link to projects for convenience %>
    <% grid
         .button(tag: :a,
                 href: projects_path,
                 scheme: :alternative,
                 class: "w-full justify-center") do |button|
    %>
      <% button.leading_icon(:arrow_left, size: :lg) %>
      <% t ".goto_initiatives" %>
    <% end %>

    <%# Link to create project %>
    <% grid
         .button(tag: :a,
                 href: new_task_path,
                 class: "w-full")
         .with_content(t ".create_task") if can? :create, Task %>
  <% end %>
<% end %>

app/views/tasks/new.html.erb
<%= render TendrilTasks::Content.new(width: :large) do %>
  <%= render TendrilTasks::Breadcrumb.new do |breadcrumb| %>
    <% breadcrumb.home %>
    <% breadcrumb.item(Task.model_name.human(count: 2), href: tasks_path) %>
    <% breadcrumb.item(@task_form.project.title,
                          href: project_path(@task_form.project)) if @task_form.project.present? %>
    <% breadcrumb.item(t("breadcrumbs.new")) %>
  <% end %>

  <%= render TendrilTasks::Heading
               .new(tag: :h1)
               .with_content(t(".title"))
  %>

  <%= render 'form', form_object: @task_form %>
<% end %>

app/views/tasks/show.html.erb
<%= render TendrilTasks::Content.new(width: :large, class: "space-y-6") do %>
  <%# Breadcrumb navigation %>
  <%= render TendrilTasks::Breadcrumb.new do |breadcrumb| %>
    <% breadcrumb.home %>
    <% breadcrumb.item(Task.model_name.human(count: 2), href: tasks_path) %>
    <% breadcrumb.item(@task.project.title, href: project_path(@task.project)) %>
    <% breadcrumb.item(@task.title) %>
  <% end %>

  <%#
    Info and action bar for editors and coordinators
    Displays published status and action buttons: edit, create task, and
    create project
  %>
  <% if can?(:coordinate, @task) ||
        can?(:update, @task) ||
        can?(:create, Project) ||
        can?(:create, Task)
  %>
    <div class="flex flex-row flex-wrap-reverse gap-4">
      <%# Visibility badges %>
      <%= render TendrilTasks::Elements::VisibilityInfoBar.new(@task) %>
      <%# Action buttons %>
      <%= render TendrilTasks::Elements::ActionBar.new(@task) %>
    </div>
  <% end %>

  <div>
    <%# Project badge %>
    <%= link_to project_path(@task.project) do %>
      <%= render Gustwave::Badge.new(@task.project.title, scheme: badge_scheme_by_id(@task.project.id), size: :lg) %>
    <% end %>
    <%# Task name %>
    <%= render TendrilTasks::Heading
                 .new(tag: :h2,
                      scheme: :level2,
                      class: "mt-2")
                 .with_content(@task.title)
    %>
    <%# Task description %>
    <%= render Gustwave::RichText.new(@task.description) %>
  </div>

  <%= render TendrilTasks::HorizontalLine.new %>

  <%# Applications %>
  <% if can?(:coordinate, @task) %>
    <%= render TendrilTasks::Heading
                 .new(tag: :h3,
                      scheme: :level3)
                 .with_content(t(".section_title.applications"))
    %>
    <div>
      <% if @task_applications.size > 0 %>
        <ol class="relative border-s border-gray-200 dark:border-gray-600 ms-3.5 mb-4 md:mb-5" id="task-applications-list">
          <% @task_applications.each do |application| %>
            <%= render TendrilTasks::Tasks::Application.new(application) %>
          <% end %>
        </ol>
      <% else %>
        <%= tag.p t(".this_task_hasnt_received_applications"),
                  class: "mb-6 text-lg font-normal text-gray-500 lg:text-xl dark:text-gray-400"
        %>
      <% end %>
    </div>
    <%= render TendrilTasks::HorizontalLine.new %>
  <% end %>

  <%# Apply to task %>
  <%= render "tasks/applications/form",
             task: @task
  %>
  <%= render TendrilTasks::HorizontalLine.new %>

  <%# Contacts %>
  <%= render TendrilTasks::Heading
               .new(tag: :h3,
                    scheme: :level3)
               .with_content(t(".contact_people"))
  %>
  <%= render TendrilTasks::Paragraph.new do %>
    <%= t(".contact_people_content") %>
  <% end %>
  <%= render Modal::ContactListComponent.new(@task.coordinators) %>
  <%= render TendrilTasks::HorizontalLine.new %>

  <div class="grid grid-cols-1 sm:grid-cols-2 justify-center text-center gap-2">
    <%= render Gustwave::Button
                 .new(tag: :a,
                      href: tasks_path,
                      scheme: :alternative,
                      size: :lg)
                 .with_content(t(".goto_tasks_button"))
    %>
    <%= render Gustwave::Button
                 .new(@task.project.title,
                      tag: :a,
                      href: project_path(@task.project),
                      scheme: :alternative,
                      size: :lg, class: "text-center justify-center") do |button|
    %>
      <% button.trailing_icon(:arrow_right) %>
    <% end %>
  </div>
<% end %>