config/routes.rb
Rails.application.routes.draw do
  # Defines the root path route ("/")
  root "pages#home"

  # Authenticate through devise and omniauth
  devise_for :users,
             controllers: { omniauth_callbacks: "users/omniauth_callbacks" },
             skip: [ :sessions ]

  # Disable the `POST "/users/sign_in"` route.
  # Prevents username/password logins. We only support omniauth.
  devise_scope :user do
    get "/users/sign_in", to: "devise/sessions#new", as: :new_user_session
    delete "/users/sign_out", to: "devise/sessions#destroy", as: :destroy_user_session
  end

  resources :tasks do
    resources :applications,
              controller: "tasks/applications",
              only: [ :create, :destroy, :update ],
              param: :user_id
    patch "/applications/:user_id/status",
          to: "tasks/applications/statuses#update",
          as: :application_status
    put "/applications/:user_id/status",
        to: "tasks/applications/statuses#update",
        as: nil
  end
  get "/tasks/new/from-preset/:project_id/:coordinator_ids", to: "tasks/from_preset#new", as: :new_task_from_preset

  resources :projects do
    resources :tasks, only: %i[ index ]
  end

  namespace :coordinators do
    resources :searches, only: %i[ index create ]
  end

  resources :dashboard, only: %i[ index ]

  resources :admin, only: %i[ index ]
  namespace :admin do
    resources :legal, only: %i[ index ]
    resource :footer, only: %i[ edit ], controller: :footer
    namespace :footer do
      resource :copyright, only: %i[ update ], controller: :copyright
      resource :sitemap, only: %i[ update destroy ], controller: :sitemap
    end
    resource :brand, only: %i[ edit ], controller: :brand
    namespace :brand do
      resource :name, only: %i[ update ], controller: :name
      resource :logo, only: %i[ update destroy ], controller: :logo
    end
    namespace :users do
      resources :roles, only: %i[ index update ]
    end
  end

  get "/profile", to: "users/profile#edit"
  delete "/profile", to: "users/profile#destroy"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :legal, param: :slug, only: %i[ show edit update destroy ], controller: "pages/legal"

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  authenticate :user, ->(user) { user.admin? } do
    mount MissionControl::Jobs::Engine, at: "/admin/monitoring/jobs"
    mount ActiveStorageDashboard::Engine, at: "/admin/monitoring/storage"
  end
end

app/views/admin/index.html.erb
<%= render TendrilTasks::Content.new(width: :large) do %>
  <%= render TendrilTasks::Breadcrumb.new do |breadcrumb| %>
    <% breadcrumb.home %>
    <% breadcrumb.item(t("breadcrumbs.admin")) %>
  <% end %>

  <%= render TendrilTasks::Heading
               .new(tag: :h1, scheme: :level2)
               .with_content(t("admin.title"))
  %>

  <%# Statistics %>
  <%= render TendrilTasks::Heading
               .new(tag: :h2, scheme: :level3)
               .with_content(t("admin.statistics.title")) %>

  <dl class="grid grid-cols-2 md:grid-cols-4 gap-4 md:gap-8">
    <%= render TendrilTasks::Admin::StatsItem
                 .new(t("admin.statistics.users.title"), @stats.users) do
    %>
      <%= render Gustwave::Badge.new("#{@stats.users[:admins]} #{t("admin.statistics.users.admins")}", scheme: :purple) %>
      <%= render Gustwave::Badge.new("#{@stats.users[:editors]} #{t("admin.statistics.users.editors")}", scheme: :indigo) %>
    <% end %>
    <%= render TendrilTasks::Admin::StatsItem
                 .new(t("admin.statistics.projects.title"), @stats.projects) do
    %>
      <%= render Gustwave::Badge.new("#{@stats.projects[:active]} #{t("admin.statistics.projects.published")}") %>
    <% end %>
    <%= render TendrilTasks::Admin::StatsItem
                 .new(t("admin.statistics.tasks.title"), @stats.tasks) do
    %>
      <%= render Gustwave::Badge.new("#{@stats.tasks[:active]} #{t("admin.statistics.tasks.published")}") %>
    <% end %>
    <%= render TendrilTasks::Admin::StatsItem
                 .new(t("admin.statistics.applications.title"), @stats.applications)
    %>
  </dl>

  <%= render Gustwave::HorizontalLine.new %>

  <%# General Settings %>
  <%= render TendrilTasks::Heading
               .new(tag: :h2)
               .with_content(t("admin.settings.title")) %>

  <ol class="grid grid-cols-1 sm:grid-cols-2 gap-4">
    <%= render TendrilTasks::Admin::Card.new do |card| %>
      <% card.heading t("admin.users.roles.title") %>
      <% card.paragraph do %>
        <%= t("admin.users.roles.description") %>
      <% end %>
      <% card.button href: admin_users_roles_path do %>
        <%= t("forms.edit") %>
      <% end %>
    <% end %>
    <%= render TendrilTasks::Admin::Card.new do |card| %>
      <% card.heading t("admin.legal.title") %>
      <% card.paragraph do %>
        <%= t("admin.legal.description") %>
      <% end %>
      <% card.button href: admin_legal_index_path do %>
        <%= t("forms.edit") %>
      <% end %>
    <% end %>
    <%= render TendrilTasks::Admin::Card.new do |card| %>
      <% card.heading t("admin.brand.title") %>
      <% card.paragraph do %>
        <%= t("admin.brand.description") %>
      <% end %>
      <% card.button href: edit_admin_brand_path do %>
        <%= t("forms.edit") %>
      <% end %>
    <% end %>
    <%= render TendrilTasks::Admin::Card.new do |card| %>
      <% card.heading t("admin.footer.title") %>
      <% card.paragraph do %>
        <%= t("admin.footer.description") %>
      <% end %>
      <% card.button href: edit_admin_footer_url do %>
        <%= t("forms.edit") %>
      <% end %>
    <% end %>
  </ol>

  <%= render Gustwave::HorizontalLine.new %>

  <%# Monitoring %>
  <%= render TendrilTasks::Heading.new(tag: :h2) do %>
    <%= t("admin.monitoring.title") %>
    <%= render TendrilTasks::Admin::ApplicationVersionBadge.new %>
  <% end %>

  <ol class="grid grid-cols-1 sm:grid-cols-2 gap-4">
    <%= render TendrilTasks::Admin::Card.new do |card| %>
      <% card.heading t("admin.monitoring.jobs.title") %>

      <% if @stats.active_job.fetch(:failed, 0) > 0 %>
        <% card.badge scheme: :red, icon: :ban do %>
          <%= t("admin.monitoring.jobs.failed", count: @stats.active_job.fetch(:failed)) %>
        <% end %>
      <% end %>

      <% if @stats.active_job.fetch(:scheduled, 0) > 0 %>
        <% card.badge scheme: :yellow, icon: :layers do %>
          <%= t("admin.monitoring.jobs.scheduled", count: @stats.active_job.fetch(:scheduled)) %>
        <% end %>
      <% end %>

      <% if @stats.active_job.fetch(:in_progress, 0) > 0 %>
        <% card.badge scheme: :indigo, icon: :hourglas do %>
          <%= t("admin.monitoring.jobs.in_progress", count: @stats.active_job.fetch(:in_progress)) %>
        <% end %>
      <% end %>

      <% if @stats.active_job.fetch(:finished, 0) > 0 %>
        <% card.badge scheme: :green, icon: :check do %>
          <%= t("admin.monitoring.jobs.finished", count: @stats.active_job.fetch(:finished)) %>
        <% end %>
      <% end %>

      <% card.paragraph do %>
        <%= t("admin.monitoring.jobs.description") %>
      <% end %>
      <% card.button href: mission_control_jobs_path do %>
        <%= t("admin.monitoring.jobs.view") %>
      <% end %>
    <% end %>
    <%= render TendrilTasks::Admin::Card.new do |card| %>
      <% card.heading t("admin.monitoring.storage.title") %>
      <% card.badge scheme: :green do %>
        <% it.leading_icon :paper_clip, class: "me-0.5" %>
        <%= t("admin.monitoring.storage.attachments", count: @stats.active_storage.fetch(:files)) %>
      <% end %>
      <% card.badge scheme: :yellow do %>
        <% it.leading_icon :file_code, class: "me-0.5" %>
        <% t("admin.monitoring.storage.blobs", count: @stats.active_storage.fetch(:blobs)) %>
      <% end %>
      <% card.badge do %>
        <% it.leading_icon :database, class: "me-0.5" %>
        <%= number_to_human_size(@stats.active_storage.fetch(:size)) %>
      <% end %>
      <% card.paragraph do %>
        <%= t("admin.monitoring.storage.description") %>
      <% end %>
      <% card.button href: active_storage_dashboard_path do %>
        <%= t("admin.monitoring.jobs.view") %>
      <% end %>
    <% end %>
  </ol>
<% end %>